# Generated by Django 5.2.7 on 2025-11-01 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание маршрута')),
                ('theme', models.CharField(choices=[('historical', 'Исторический'), ('religious', 'Религиозный'), ('nature', 'Природоведческий'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Тематика')),
                ('transport_type', models.CharField(choices=[('foot', 'Пеший'), ('bike', 'Велосипед'), ('car', 'Автомобиль'), ('boat', 'Лодка'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Тип транспорта')),
                ('duration_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)], verbose_name='Длительность (часов)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('need_food_supply', models.BooleanField(default=False, verbose_name='Нужен запас еды')),
                ('max_participants', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимум участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('start_lat', models.FloatField(blank=True, null=True, verbose_name='Широта старта')),
                ('start_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота старта')),
                ('end_lat', models.FloatField(blank=True, null=True, verbose_name='Широта финиша')),
                ('end_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота финиша')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок совета')),
                ('description', models.TextField(verbose_name='Описание совета')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='routes.route')),
            ],
            options={
                'verbose_name': 'Совет по маршруту',
                'verbose_name_plural': 'Советы по маршруту',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название точки')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('history_info', models.TextField(blank=True, verbose_name='Историческая справка')),
                ('visit_notes', models.TextField(blank=True, help_text='Рекомендации по времени посещения, что взять с собой и т.д.', verbose_name='Особенности посещения')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('moderate', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=20, verbose_name='Сложность посещения')),
                ('best_visit_time', models.CharField(blank=True, max_length=100, verbose_name='Лучшее время для посещения')),
                ('visiting_season', models.CharField(blank=True, max_length=100, verbose_name='Сезон посещения')),
                ('estimated_stay_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(480)], verbose_name='Рекомендуемое время на посещение (минут)')),
                ('has_food', models.BooleanField(default=False, verbose_name='Есть питание')),
                ('has_toilets', models.BooleanField(default=False, verbose_name='Есть туалеты')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Есть парковка')),
                ('is_wheelchair_accessible', models.BooleanField(default=False, verbose_name='Доступно для инвалидов')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Опциональная точка')),
                ('order', models.IntegerField(verbose_name='Порядковый номер в маршруте')),
                ('waypoint_type', models.CharField(choices=[('attraction', 'Достопримечательность'), ('food', 'Точка питания'), ('info', 'Информационная точка'), ('view', 'Смотровая площадка'), ('start', 'Старт'), ('end', 'Финиш'), ('break', 'Место отдыха'), ('shrine', 'Святыня, храм'), ('skete', 'Скит'), ('museum', 'Музей'), ('nature', 'Природа')], max_length=20, verbose_name='Тип точки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='Высота над уровнем моря (м)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WaypointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200x800px', upload_to='waypoints/%Y/%m/%d/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='routes.waypoint')),
            ],
            options={
                'verbose_name': 'Изображение точки',
                'verbose_name_plural': 'Изображения точек',
                'ordering': ['waypoint', 'order', 'is_primary'],
            },
        ),
    ]
