# Generated by Django 5.2.7 on 2025-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='best_visit_time',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='visiting_season',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='architecture_info',
            field=models.TextField(blank=True, help_text='Описание архитектурных особенностей, стиля, материалов', verbose_name='Архитектура и особенности'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='best_time_to_visit',
            field=models.TextField(blank=True, help_text='Рекомендуемое время суток, сезон, погодные условия', verbose_name='Лучшее время для посещения'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Полное описание достопримечательности, её особенностей и значимости', verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='path_description',
            field=models.TextField(blank=True, help_text='Как добраться до точки, особенности маршрута, сложности пути', verbose_name='Описание пути'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='history_info',
            field=models.TextField(blank=True, help_text='Исторические факты, даты строительства, значимые события', verbose_name='Историческая справка'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='short_description',
            field=models.TextField(blank=True, help_text='Краткое описание для карточек и списков (до 1000 символов)', verbose_name='Краткое описание точки'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='visit_notes',
            field=models.TextField(blank=True, help_text='Рекомендации по времени посещения, что взять с собой, особенности поведения', verbose_name='Особенности посещения'),
        ),
        migrations.AlterField(
            model_name='waypointimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Подробное описание фотографии', verbose_name='Подпись к фото'),
        ),
    ]
